### ISSUE TITLE
 New Device Logged In From Temporary device name 

### ISSUE THREAD

**Issue by uxes** [ilyakooo0/warden#13]
I'v got mail that i logged from " Temporary device name " it took me for a while to understand this stuff.

It seems that device name could be considered to be changed https://github.com/ilyakooo0/warden/blob/4f8e87887795d6348912c35628ebe6789b6efe00/backend/BW/Logic.purs#L115

**Comment by ilyakooo0** [comment]
This will be resolved as part of #10
