### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by stemy2** [ilyakooo0/warden#6]
Hello,

I can't login, it says "token not found" then loads indefinitely.

**Comment by ilyakooo0** [comment]
Does your account requires 2FA?

**Comment by stemy2** [comment]
Yes. Have i to delete it ?

**Comment by ilyakooo0** [comment]
The app currently does not support 2FA. 

Unfortunately, I forgot to mention this anywhre (:

**Comment by ilyakooo0** [comment]
If you disable 2FA things should work

**Comment by stemy2** [comment]
The other problem with 2FA is that i don't show the OTP code for the accounts that have one. So the app is now nearly useless for my use, except if i disable otp from all my accounts saved in my vault, and i don't want to.
